# Generated by Django 3.2.5 on 2021-10-03 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(default='default color', max_length=10),
        ),
    ]
