# Generated by Django 3.2.5 on 2021-10-03 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_product_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='contect',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=50)),
                ('comment', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
