# Generated by Django 3.2.5 on 2021-10-11 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20211010_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='items',
            field=models.CharField(default='', max_length=300),
        ),
    ]
