# Generated by Django 3.2.5 on 2021-10-11 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_orders_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='total_rs',
            field=models.CharField(default=' ', max_length=90),
        ),
    ]
