# Generated by Django 3.2.5 on 2021-10-11 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_alter_orders_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='items',
            field=models.JSONField(default='{}', max_length=300),
        ),
    ]
